### ISSUE TITLE
Need help setting this up :)

### ISSUE THREAD

**Issue by yjukaku** [alsemyonov/graphiti-openapi#5]
Hello, thanks for your work on this gem! I'd love to get this working, but I think I need your help.

I'm testing out Graphiti v1.2.1 and I can't seem to get this gem to be able to generate an OpenAPI doc. Here were my steps to get started with this gem (Graphiti is already setup and working fine).

1. `bin/rails graphiti:openapi:install`
2. Add `= javascript_pack_tag "api", crossorigin: "anonymous"` to my `application.slim`
3. Update `api.js` to point to the correct `url`, in our case `/api/v3/openapi.json`

Unfortunately, it looks like that file is not being generated.
I took a look at the gem's source and tried running `bin/rails graphiti:openapi:generate --verbose`, however, I'm getting an error about `Dry::Types`:

```
** Invoke graphiti:openapi:generate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke public/schemas/jsonapi.json (first_time, not_needed)
** Execute graphiti:openapi:generate
[dry-types] Dry::Types.module is deprecated and will be removed in the next major version
Use Dry.Types() instead. Beware, it exports strict types by default, for old behavior use Dry.Types(default: :nominal). See more options in the changelog
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
rails aborted!
NoMethodError: undefined method `member_types' for #<Dry::Types[Constructor<Schema<keys={}> fn=Kernel.Hash>]>
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/dry-types-0.15.0/lib/dry/types/constructor.rb:147:in `method_missing'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/dry-struct-0.6.0/lib/dry/struct/class_interface.rb:326:in `schema'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/dry-struct-0.6.0/lib/dry/struct/class_interface.rb:213:in `check_schema_duplication'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/dry-struct-0.6.0/lib/dry/struct/class_interface.rb:153:in `attributes'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/dry-struct-0.6.0/lib/dry/struct/class_interface.rb:103:in `attribute'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/graphiti-openapi-0.1.7/app/models/graphiti/open_api/attribute.rb:6:in `<class:AttributeData>'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/graphiti-openapi-0.1.7/app/models/graphiti/open_api/attribute.rb:5:in `<module:OpenAPI>'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/graphiti-openapi-0.1.7/app/models/graphiti/open_api/attribute.rb:4:in `<top (required)>'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/graphiti-openapi-0.1.7/app/models/graphiti/open_api/resource.rb:4:in `require_relative'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/graphiti-openapi-0.1.7/app/models/graphiti/open_api/resource.rb:4:in `<top (required)>'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/graphiti-openapi-0.1.7/app/models/graphiti/open_api/schema.rb:3:in `require_relative'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/graphiti-openapi-0.1.7/app/models/graphiti/open_api/schema.rb:3:in `<top (required)>'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/graphiti-openapi-0.1.7/app/models/graphiti/open_api/generator.rb:5:in `require_relative'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/graphiti-openapi-0.1.7/app/models/graphiti/open_api/generator.rb:5:in `<top (required)>'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:476:in `load'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:476:in `block in load_file'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:661:in `new_constants_in'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:475:in `load_file'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:373:in `block in require_or_load'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:37:in `load_interlock'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:356:in `require_or_load'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:510:in `load_missing_constant'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:195:in `const_missing'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/graphiti-openapi-0.1.7/lib/tasks/graphiti_openapi.rake:19:in `block (3 levels) in <top (required)>'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/command.rb:48:in `invoke'
/Users/yj/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => graphiti:openapi:generate
```

Any suggestions? I'd guess there's a breaking change in Dry::Types from too loose of a dependency?

**Comment by chedim** [comment]
Hey, 

Unfortunately, and as far as I know, @alsemyonov is no longer with us so... probably no updates for the project anymore. 

He was a hero of Russian LGBT rights movement and loosing him is a terrible thing for both communities.

**Comment by yjukaku** [comment]
I'm sorry to hear that. Maybe it'd be a good idea to open a new issue on the repo explaining that.
